### ISSUE TITLE
Allow branch selection

### ISSUE THREAD

**Issue by maaaaarco** [mschmidtkorth/msk-sfdx-toolbox#3]
Currently the script is comparing the selected Permission Set or Profile against the version on the _master_ branch. Allow users to select the branch to compare.

**Desired solution**
After the selection of Profile or Permission Set present a list of possible branches. _master_ should be the default.

**Comment by mschmidtkorth** [comment]
Agree, comparing against master will be the most likely but not the only scenario.

**Comment by maaaaarco** [comment]
Maybe we can provide two commands, one to compare against the _master_ and another one that allows you to select the other branch.
- Compare Permissions
- Compare Permissions with branch...

**Comment by mschmidtkorth** [comment]
Yes, we could also add an alternative command (`opt`) so we don't need to duplicate them. But might not be ideal from a UX perspective. For now I've implemented a simple selection. Feel free to add a default!
